language: ruby
rvm:
  - 2.1.7
  - 2.3.1
  - 2.4.1

# User container based travis infrastructure which allows caching
# features for open source projects.
sudo: false

env:
  - ACTIVATE_BEFORE_SETUP=true
  - ACTIVATE_BEFORE_SETUP=false

before_install:
  - gem update --system 2.6.14
  - gem list
  - rvm @global do gem uninstall bundler -a -x
  - gem list
  - rvm @global do gem install bundler -v 1.15.4
  - bundle --version
  - gem --version

script:
  - gem list
  - ruby ./script.rb
