language: ruby
rvm:
  - 2.1.7
#  - 2.3.1
#  - 2.4.1

# User container based travis infrastructure which allows caching
# features for open source projects.
sudo: false

env:
  - ACTIVATE_BEFORE_SETUP=true
  - ACTIVATE_BEFORE_SETUP=false

before_install:
  - ls /home/travis/.rvm/rubies/ruby-2.1.7/lib/ruby/site_ruby/exe || ls /home/travis/.rvm/rubies/ruby-2.1.7/lib/ruby/site_ruby
  - rvm @global do gem uninstall rubygems-update --all -x
  - rvm @global do gem uninstall bundler --all -x
  - rvm @global do gem update --system 2.6.14
  - rvm @global do gem install bundler
  - bundle --version
  - gem --version

script:
  - gem list
  - ruby ./script.rb
