language: ruby
rvm:
  - 2.1.7
  - 2.3.1
  - 2.4.1

# User container based travis infrastructure which allows caching
# features for open source projects.
sudo: false

env:
  - ACTIVATE_BEFORE_SETUP=true
  - ACTIVATE_BEFORE_SETUP=false

install: bundle install

script:
  - gem list
  - ruby ./script.rb
